export const menu =[
 {
    'es': [{
        "titulo":"perfil",
        "icono":"icono",
        "url":"enlace"
    },
    {
        "titulo":"perfil",
        "icono":"icono",
        "url":"enlace"
    },
    {
        "titulo":"perfil",
        "icono":"icono",
        "url":"enlace"
    },
    {
        "titulo":"perfil",
        "icono":"icono",
        "url":"enlace"
    },
    {
        "titulo":"perfil",
        "icono":"icono",
        "url":"enlace"
    },]
 }
];